font_size 14
background_opacity 0.4
dynamic_background_opacity yes
allow_remote_control

# BEGIN_KITTY_FONTS
font_family      family='Hack Nerd Font Mono' postscript_name=HackNFM-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# Some more personal tweaks
scrollback_lines 10000
hide_window_decorations yes
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
notify_on_cmd_finish invisible

cursor_trail 200
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# My keybindings that I like
map ctrl+shift+k scroll_page_up
map ctrl+shift+j scroll_page_down

map ctrl+shift+l next_tab
map ctrl+shift+h previous_tab

# Include the theme files to make it easier to switch
include $HOME/.config/kitty/kitty-theme.conf
