[keybindings]
"Space" = "playpause"
"Enter" = "play"
"e" = "seek +1000"
"Shift+e" = "seek 10000"
"Shift+q" = "queue"
"Shift+s" = "shuffle"
"Ctrl+q" = "focus queue"
"Ctrl+s" = "focus search"
"Ctrl+l" = "focus library"
"Ctrl+c" = "focus cover"
"$" = "next"
"0" = "previous"
"=" = "volup 1"
"Esc" = "back"
